extend type Document {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Document", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Document`.`license`. It must match the value of `License`.`id`. See `@ref` for how to customize it.
  """
  licenseId: UUID @fdc_generated(from: "Document.license", purpose: IMPLICIT_REF_FIELD)
}
extend type License {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "License", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `License`.`licenseType`. It must match the value of `LicenseType`.`id`. See `@ref` for how to customize it.
  """
  licenseTypeId: UUID @fdc_generated(from: "License.licenseType", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `License`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID @fdc_generated(from: "License.user", purpose: IMPLICIT_REF_FIELD)
}
extend type LicenseType {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "LicenseType", purpose: IMPLICIT_KEY_FIELD)
}
extend type Notification {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Notification", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Notification`.`license`. It must match the value of `License`.`id`. See `@ref` for how to customize it.
  """
  licenseId: UUID @fdc_generated(from: "Notification.license", purpose: IMPLICIT_REF_FIELD)
}
extend type User {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "User", purpose: IMPLICIT_KEY_FIELD)
}
