# This file deploys to PRODUCTION when code is merged to the 'main' branch

name: Deploy to Firebase Hosting - Production
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy_prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci && npm run build
        env:
          # Aquí se deben usar los secretos específicos para el proyecto de producción real
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY_PRD }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN_PRD }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID_PRD }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET_PRD }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID_PRD }}
          VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID_PRD }}
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_GLICENSE_PRD }}
          channelId: live
          projectId: g-license-mgr-dev-gsv000-015
